services:
  upset:
    build:
      context: .
      dockerfile: Dockerfile

    image: upset-runtime:ubuntu20.04
    container_name: upset

    network_mode: host

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      UPSET_INSTALL_DIR: /opt/upset/INSTALL

    volumes:
      - ./.upset:/opt/upset
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    working_dir: /workspace

    stdin_open: true
    tty: true
